-- =====================================================
-- ACERVO TI - DADOS OPERACIONAIS MULTI-TENANT
-- Execute este arquivo no SQL Editor do Supabase uma vez.
-- O aplicativo local continua usando SQLite ate a migracao.
-- =====================================================

create table if not exists public.ativos (
    id text not null,
    colegio_id uuid not null references public.colegios(id) on delete cascade,
    numero_carrinho integer,
    tipo text not null default 'Notebook',
    modelo text,
    numero_serie text,
    data_compra text,
    status text not null default 'Disponível',
    localizacao text,
    observacoes text,
    data_cadastro text not null default now()::text,
    primary key (colegio_id, id),
    unique (colegio_id, numero_carrinho)
);

create table if not exists public.configuracoes_sistema (
    colegio_id uuid not null references public.colegios(id) on delete cascade,
    chave text not null,
    valor text,
    primary key (colegio_id, chave)
);

create table if not exists public.sessoes_uso (
    id bigint generated by default as identity primary key,
    colegio_id uuid not null references public.colegios(id) on delete cascade,
    source_id text not null,
    turma text,
    professor text,
    programa text,
    data_inicio text not null default now()::text,
    quantidade_notebooks integer,
    observacoes text,
    previsao_devolucao text,
    usuario_movimentacao text,
    unique (colegio_id, source_id)
);

create table if not exists public.problemas (
    id bigint generated by default as identity primary key,
    colegio_id uuid not null references public.colegios(id) on delete cascade,
    source_id text not null,
    ativo_id text,
    tipo_problema text,
    descricao text,
    data_registro text not null default now()::text,
    responsavel text,
    status text,
    prioridade text not null default 'Normal',
    categoria text not null default 'Hardware',
    parecer_tecnico text,
    local_incidente text not null default 'NÃO INFORMADO',
    data_resolucao text,
    foreign key (colegio_id, ativo_id) references public.ativos(colegio_id, id) on delete cascade,
    unique (colegio_id, source_id)
);

create table if not exists public.historico (
    id bigint generated by default as identity primary key,
    colegio_id uuid not null references public.colegios(id) on delete cascade,
    source_id text not null,
    id_etiqueta text,
    acao text,
    usuario_movimentacao text,
    responsavel text not null default '-',
    data text not null default now()::text,
    obs text,
    unique (colegio_id, source_id)
);

create table if not exists public.agendamentos (
    id bigint generated by default as identity primary key,
    colegio_id uuid not null references public.colegios(id) on delete cascade,
    source_id text not null,
    solicitante text,
    data_uso text,
    periodo text,
    quantidade integer,
    finalidade text,
    itens_reservados text,
    horario_retirada text,
    horario_devolucao text,
    status text not null default 'Agendado',
    data_criacao text not null default now()::text,
    registrado_por text,
    codigo_reserva text,
    unique (colegio_id, source_id)
);

create table if not exists public.almox_produtos (
    id bigint generated by default as identity primary key,
    colegio_id uuid not null references public.colegios(id) on delete cascade,
    source_id text not null,
    sku text not null,
    nome text not null,
    categoria text,
    quantidade_atual integer not null default 0,
    estoque_minimo integer not null default 5,
    custo_unitario double precision not null default 0,
    unique (colegio_id, sku),
    unique (colegio_id, source_id)
);

create table if not exists public.almox_movimentacoes (
    id bigint generated by default as identity primary key,
    colegio_id uuid not null references public.colegios(id) on delete cascade,
    source_id text not null,
    produto_source_id text not null,
    tipo text not null,
    quantidade integer not null,
    usuario text,
    destino_id text,
    data_movimentacao text not null default now()::text,
    observacao text,
    unique (colegio_id, source_id),
    foreign key (colegio_id, produto_source_id)
        references public.almox_produtos(colegio_id, source_id)
        on delete restrict
);

create index if not exists idx_ativos_colegio on public.ativos (colegio_id);
create index if not exists idx_sessoes_uso_colegio on public.sessoes_uso (colegio_id);
create index if not exists idx_problemas_colegio on public.problemas (colegio_id);
create index if not exists idx_historico_colegio on public.historico (colegio_id);
create index if not exists idx_agendamentos_colegio on public.agendamentos (colegio_id);
create index if not exists idx_almox_produtos_colegio on public.almox_produtos (colegio_id);
create index if not exists idx_almox_movimentacoes_colegio on public.almox_movimentacoes (colegio_id);

alter table public.ativos enable row level security;
alter table public.configuracoes_sistema enable row level security;
alter table public.sessoes_uso enable row level security;
alter table public.problemas enable row level security;
alter table public.historico enable row level security;
alter table public.agendamentos enable row level security;
alter table public.almox_produtos enable row level security;
alter table public.almox_movimentacoes enable row level security;

create policy "tenant_access" on public.ativos for all to authenticated
using (colegio_id = public.current_user_colegio_id())
with check (colegio_id = public.current_user_colegio_id());

create policy "tenant_access" on public.configuracoes_sistema for all to authenticated
using (colegio_id = public.current_user_colegio_id())
with check (colegio_id = public.current_user_colegio_id());

create policy "tenant_access" on public.sessoes_uso for all to authenticated
using (colegio_id = public.current_user_colegio_id())
with check (colegio_id = public.current_user_colegio_id());

create policy "tenant_access" on public.problemas for all to authenticated
using (colegio_id = public.current_user_colegio_id())
with check (colegio_id = public.current_user_colegio_id());

create policy "tenant_access" on public.historico for all to authenticated
using (colegio_id = public.current_user_colegio_id())
with check (colegio_id = public.current_user_colegio_id());

create policy "tenant_access" on public.agendamentos for all to authenticated
using (colegio_id = public.current_user_colegio_id())
with check (colegio_id = public.current_user_colegio_id());

create policy "tenant_access" on public.almox_produtos for all to authenticated
using (colegio_id = public.current_user_colegio_id())
with check (colegio_id = public.current_user_colegio_id());

create policy "tenant_access" on public.almox_movimentacoes for all to authenticated
using (colegio_id = public.current_user_colegio_id())
with check (colegio_id = public.current_user_colegio_id());