"""Adiciona campo last_login a tabela de usuarios

Revision ID: 625433ac80ef
Revises: 608cc5503b3d
Create Date: 2026-07-01 17:02:52.323732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625433ac80ef'
down_revision = '608cc5503b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('almox_movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    with op.batch_alter_table('almox_movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
