"""Adiciona a coluna last_login na tabela Usuario

Revision ID: a1843cbf46a8
Revises: b9192546d5c8
Create Date: 2026-08-11 12:43:52.548642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1843cbf46a8'
down_revision = 'b9192546d5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('almox_movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.alter_column('data_compra',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('data_cadastro',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.alter_column('data_registro',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('data_resolucao',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('sessoes_uso', schema=None) as batch_op:
        batch_op.alter_column('previsao_devolucao',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessoes_uso', schema=None) as batch_op:
        batch_op.alter_column('previsao_devolucao',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.alter_column('data_resolucao',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('data_registro',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('data_compra',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('almox_movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
