"""Altera data_cadastro para String para compatibilidade

Revision ID: d59c1c0b5bf8
Revises: e5d1bb1d399c
Create Date: 2026-07-01 17:16:10.898091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59c1c0b5bf8'
down_revision = 'e5d1bb1d399c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('almox_movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('almox_movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
