"""Corrige tipo da coluna data_movimentacao

Revision ID: e5d1bb1d399c
Revises: 625433ac80ef
Create Date: 2026-07-01 17:11:21.178009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d1bb1d399c'
down_revision = '625433ac80ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('almox_movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('almox_movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
