-- =====================================================
-- CORREÇÃO DA SINCRONIZAÇÃO: usuários + almoxarifado
-- Execute no SQL Editor do Supabase (Dashboard).
-- Seguro para rodar mais de uma vez (idempotente).
-- =====================================================

-- =====================================================
-- 1) CRIA A TABELA usuarios (não existe ainda na nuvem)
-- =====================================================
create table if not exists public.usuarios (
    id bigint generated by default as identity primary key,
    colegio_id uuid not null references public.colegios(id) on delete cascade,
    source_id text not null,
    username text not null,
    password text not null,
    perm_movimentacao boolean not null default false,
    perm_cadastro boolean not null default false,
    perm_config boolean not null default false,
    perm_kiosk boolean not null default false,
    perm_chamados boolean not null default false,
    perm_ajuda boolean not null default false,
    perm_almoxarifado boolean not null default false,
    last_login text,
    unique (colegio_id, username),
    unique (colegio_id, source_id)
);

alter table public.usuarios enable row level security;

drop policy if exists "tenant_access" on public.usuarios;
create policy "tenant_access" on public.usuarios for all to authenticated
using (colegio_id = public.current_user_colegio_id())
with check (colegio_id = public.current_user_colegio_id());

create index if not exists idx_usuarios_colegio on public.usuarios (colegio_id);

-- =====================================================
-- 2) MIGRA A TABELA almox_movimentacoes para o modelo novo
--    (troca produto_id -> produto_source_id, com backfill)
-- =====================================================

-- 2a) Garante as colunas novas
alter table public.almox_movimentacoes add column if not exists source_id text;
alter table public.almox_movimentacoes add column if not exists produto_source_id text;

-- 2b) Backfill das linhas antigas (só preenche o que estiver nulo)
update public.almox_movimentacoes
set source_id = coalesce(source_id, id::text)
where source_id is null;

update public.almox_movimentacoes m
set produto_source_id = coalesce(m.produto_source_id, p.source_id)
from public.almox_produtos p
where m.produto_source_id is null
  and p.colegio_id = m.colegio_id
  and p.id = m.produto_id;

-- 2c) Remove a constraint NOT NULL antiga da coluna produto_id
--     (o código novo não envia mais esse campo)
do $$
begin
    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public'
          and table_name = 'almox_movimentacoes'
          and column_name = 'produto_id'
          and is_nullable = 'NO'
    ) then
        alter table public.almox_movimentacoes alter column produto_id drop not null;
    end if;
end $$;

-- 2d) Torna as colunas novas obrigatórias (só se nenhum valor nulo restou)
do $$
begin
    if not exists (select 1 from public.almox_movimentacoes where source_id is null) then
        alter table public.almox_movimentacoes alter column source_id set not null;
    end if;
    if not exists (select 1 from public.almox_movimentacoes where produto_source_id is null) then
        alter table public.almox_movimentacoes alter column produto_source_id set not null;
    end if;
end $$;

-- 2e) Garante o índice único usado pelo upsert (colegio_id, source_id)
do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'almox_movimentacoes_source_id_key'
    ) then
        -- Cria índice único (mais seguro que constraint se houver duplicados)
        create unique index if not exists almox_movimentacoes_source_id_key
            on public.almox_movimentacoes (colegio_id, source_id);
    end if;
end $$;

-- 2f) Garante a FK para o produto (referência pelo par colegio+source_id)
do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'almox_movimentacoes_produto_source_fkey'
    ) then
        alter table public.almox_movimentacoes
            add constraint almox_movimentacoes_produto_source_fkey
            foreign key (colegio_id, produto_source_id)
            references public.almox_produtos(colegio_id, source_id)
            on delete restrict;
    end if;
end $$;

-- =====================================================
-- 3) VERIFICAÇÃO FINAL (deve retornar 'usuarios OK' e 'movimentacoes OK')
-- =====================================================
select case
    when to_regclass('public.usuarios') is not null then 'usuarios OK'
    else 'FALHOU: usuarios nao criada' end as check_1;

select case
    when exists (
        select 1 from information_schema.columns
        where table_schema='public' and table_name='almox_movimentacoes'
          and column_name='produto_source_id'
    ) then 'movimentacoes OK'
    else 'FALHOU: produto_source_id ausente' end as check_2;
